Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"
  config.vm.box_version = "1.0.282"
  config.vm.provision "docker"
  config.vm.provision "docker_compose"

  config.vm.provider "vmware_desktop" do |v|
    v.vmx["memsize"] = "2024"
    v.vmx["numvcpus"] = "2"
  end

  (1..5).each do |i|
    config.vm.define "node-#{i}" do |node|
      node.vm.hostname = "node-#{i}"

      node.vm.provision "file",
        source: "../github_actions_runner",
        destination: "github_actions_runner"

# move to setup.sh
      node.vm.provision "shell",
        inline: "cd github_actions_runner/actions-runner && tar xzf ./actions-runner-linux-x64-2.276.1.tar.gz",
        privileged: false

      node.vm.provision "shell",
        inline: "cd github_actions_runner && ./setup.sh"

      node.vm.provision "shell",
        inline: "echo node #{i} online"

      node.trigger.before :destroy do |trigger|
        trigger.warn = "removing github actions runner"
        trigger.run_remote = {inline: "bash -c 'cd github_actions_runner && ./remove.sh'"}
      end

    end
  end
end
