Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2004"
  config.vm.provision "docker"
  config.vm.provision "docker_compose"

  config.vm.provider "virtualbox" do |v|
    v.memory = 3584
    v.cpus = 3
  end

  (1..3).each do |i|
    config.vm.define "node-#{i}" do |node|
      node.vm.hostname = "node-#{i}"

      node.vm.provision "file",
        source: "../github_actions_runner",
        destination: "github_actions_runner"

      node.vm.provision "shell",
        inline: "cd github_actions_runner && ./setup.sh",
        privileged: false

      node.vm.provision "shell",
        inline: "echo node #{i} online"

      node.trigger.before :destroy do |trigger|
        trigger.warn = "removing github actions runner"
        trigger.run_remote = {inline: "bash -c 'cd github_actions_runner && ./remove.sh'", privileged: false}
        trigger.on_error = :continue
      end

    end
  end
end
